### ISSUE TITLE
Add InfluxQL compatibility | 兼容InfluxQL

### ISSUE THREAD

**Issue by muninshen** [cnosdatabase/cnosdb#2]
# In English | [中文版](#chinese)
### Background
In terms of query, CnosDB would like to be compatible to the most popular TSDB - InfluxDB, where InfluxQL is the main query language.

### Problem
There are some discrepancies between the two. See InfluxQL spec here: https://docs.influxdata.com/influxdb/v1.8/query_language/

### Proposal
Following key terms should be renamed:
* metric  -> measurement
* ttl         -> retention policy
* region  -> shard group

<h1 id="chinese">中文版</h2>

### 背景
至少在查询层面，CnosDB期望与当前最流行的时序数据库产品即InfluxDB保持兼容。其InfluxQL应参考学习。

### 问题
目前，有若干关键术语俩产品存在不一致。具体的标准可参考：https://docs.influxdata.com/influxdb/v1.8/query_language/

### 建议
建议如下术语应做统一更改：
* metric  -> measurement
* ttl         -> retention policy
* region  -> shard group

**Comment by IvanGao01** [comment]
This issue is completed.
